[template]
keys        = [ "elasticsearch/host" ]
owner       = "nginx"
mode        = "0644"
src         = "nginx_sinatra.conf.tmpl"
dest        = "/etc/nginx/sites-enabled/sinatra.conf"
check_cmd   = "/usr/sbin/nginx -t -c /etc/nginx/sinatra.conf"
reload_cmd  = "/usr/sbin/service nginx reload"
